// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeApp.Server.Data;

#nullable disable

namespace ResumeApp.Server.Migrations
{
    [DbContext(typeof(ResumeDbContext))]
    [Migration("20260412184041_Updated the Certifications section")]
    partial class UpdatedtheCertificationssection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResumeApp.Server.Model.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CredentialUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("YearObtained")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Certifcations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CredentialUrl = "",
                            DisplayOrder = 1,
                            Issuer = "Udemy",
                            Name = ".NET Core Developer Certification",
                            ResumeId = 1,
                            YearObtained = 2025
                        },
                        new
                        {
                            Id = 2,
                            CredentialUrl = "",
                            DisplayOrder = 2,
                            Issuer = "Udemy",
                            Name = ".NET Core API Developer Certification",
                            ResumeId = 1,
                            YearObtained = 2025
                        },
                        new
                        {
                            Id = 3,
                            CredentialUrl = "",
                            DisplayOrder = 3,
                            Issuer = "Coursera",
                            Name = "Google IT Support Professional Certificate",
                            ResumeId = 1,
                            YearObtained = 2024
                        },
                        new
                        {
                            Id = 4,
                            CredentialUrl = "",
                            DisplayOrder = 4,
                            Issuer = "Udacity",
                            Name = "SQL for Data Analysis",
                            ResumeId = 1,
                            YearObtained = 2022
                        });
                });

            modelBuilder.Entity("ResumeApp.Server.Model.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Metclan Technologies",
                            Description = "Developed 3+ full-stack applications using ASP.NET Core Web API and React.|Built reusable React components, reducing development time by 30%.|Integrated REST APIs and optimized queries with Entity Framework Core, improving performance by 25%.|Implemented CI/CD pipelines using GitHub Actions and Azure DevOps.|Collaborated in an Agile team using Git for version control.",
                            Duration = "2025 - 2026",
                            ResumeId = 1,
                            Role = "Full-Stack .NET Developer"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Loctech Training Institute",
                            Description = "Developed applications using .NET, C#, HTML, CSS, JavaScript, and jQuery.|Contributed to the development of a healthcare management system, improving patient record handling and data accessibility.|Diagnosed and resolved 20+ software bugs, enhancing system reliability and user satisfaction.|Assisted in application testing, debugging, and deployment processes.",
                            Duration = "2024 - 2025",
                            ResumeId = 1,
                            Role = "Software Developer"
                        },
                        new
                        {
                            Id = 3,
                            Company = "FirstBank Limited",
                            Description = "Installed, customized, and supported desktop and laptop workstations plus software systems for 100+ in-office and remote users.|Refurbished 100+ Windows 8 machines to Windows 10 in preparation for an Office 365 rollout across eight regional offices.|Mentored junior team members and supported IT systems operations.|Managed cloud migration for storage and backup systems.|Handled 20 to 40 onsite IT support calls daily.",
                            Duration = "2021 - 2024",
                            ResumeId = 1,
                            Role = "IT/Network Specialist"
                        });
                });

            modelBuilder.Entity("ResumeApp.Server.Model.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full-stack resume application with responsive design, deployed to Azure cloud.",
                            DisplayOrder = 1,
                            GithubUrl = "",
                            Name = "Resume Website (This Project)",
                            ProjectUrl = "",
                            ResumeId = 1,
                            Technologies = "React + Vite frontend, ASP.NET Core backend, Azure App Service"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Full-stack task management system with CRUD operations, authentication, and responsive UI.",
                            DisplayOrder = 2,
                            GithubUrl = "",
                            Name = "Task Management API with React Frontend",
                            ProjectUrl = "",
                            ResumeId = 1,
                            Technologies = "ASP.NET Core Web API, React, SQL Server, Entity Framework"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Complete e-commerce solution with product management, shopping cart, and order processing.",
                            DisplayOrder = 3,
                            GithubUrl = "",
                            Name = "E-Commerce MVC Application",
                            ProjectUrl = "",
                            ResumeId = 1,
                            Technologies = "ASP.NET Core MVC, HTML 5, CSS 3, JavaScript, SQL Server"
                        },
                        new
                        {
                            Id = 4,
                            Description = "RESTful API for hotel room booking with customer management and reservation tracking.",
                            DisplayOrder = 4,
                            GithubUrl = "",
                            Name = "Hotel Booking API",
                            ProjectUrl = "",
                            ResumeId = 1,
                            Technologies = "ASP.NET Core Web API, SQL Server, Entity Framework"
                        });
                });

            modelBuilder.Entity("ResumeApp.Server.Model.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Nigeria",
                            Email = "wisdomf41@gmail.com",
                            Name = "Future Ibeche",
                            Stack = "React | SQL | ASP.NET Core | REST API",
                            Summary = "Full-Stack .NET Developer with experience in building full-stack applications using C#, ASP.NET Core Web API, and React. Skilled in developing RESTful APIs, SQL Server, and Entity Framework Core, with a focus on performance and scalability. Experienced in implementing CI/CD pipelines (GitHub Actions/Azure DevOps) to automate builds and deployments. Strong collaborator in Agile and remote teams, passionate about building efficient, maintainable systems.",
                            Title = "C# /.NET Developer",
                            Url = "GitHub / LinkedIn (@wisdomf41)"
                        });
                });

            modelBuilder.Entity("ResumeApp.Server.Model.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            DisplayOrder = 1,
                            ResumeId = 1,
                            Skills = "C#, .NET Core Web API, REST APIs"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Database",
                            DisplayOrder = 2,
                            ResumeId = 1,
                            Skills = "SQL Server, Entity Framework Core, LINQ"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Frontend",
                            DisplayOrder = 3,
                            ResumeId = 1,
                            Skills = "React, HTML 5, CSS3, JavaScript (ES6+), Vite"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tools",
                            DisplayOrder = 4,
                            ResumeId = 1,
                            Skills = "Git, GitHub, Visual Studio, Azure"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Concepts",
                            DisplayOrder = 5,
                            ResumeId = 1,
                            Skills = "Full-Stack Development, API Integration, Component-Based Architecture, Authentication & Authorization"
                        });
                });

            modelBuilder.Entity("ResumeApp.Server.Model.Certification", b =>
                {
                    b.HasOne("ResumeApp.Server.Model.Resume", "Resume")
                        .WithMany()
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.Server.Model.Experience", b =>
                {
                    b.HasOne("ResumeApp.Server.Model.Resume", "Resume")
                        .WithMany()
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.Server.Model.Project", b =>
                {
                    b.HasOne("ResumeApp.Server.Model.Resume", "Resume")
                        .WithMany()
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.Server.Model.Skill", b =>
                {
                    b.HasOne("ResumeApp.Server.Model.Resume", "Resume")
                        .WithMany()
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });
#pragma warning restore 612, 618
        }
    }
}
