// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeApp.Server.Data;

#nullable disable

namespace ResumeApp.Server.Migrations
{
    [DbContext(typeof(ResumeDbContext))]
    [Migration("20260402171111_Seeded Url, Stack, Country and Summary")]
    partial class SeededUrlStackCountryandSummary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResumeApp.Server.Model.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Nigeria",
                            Email = "wisdomf41@gmail.com",
                            Name = "Future Ibeche",
                            Stack = "React | SQL | ASP.NET Core | Rest API",
                            Summary = "Full-Stack .NET Developer with experience in building full-stack applications using C#, ASP.NET Core Web API, and React. Skilled in developing RESTful APIs, SQL Server, and Entity Framework Core, with a focus on performance and scalability. Experienced in implementing CI/CD pipelines (GitHub Actions/Azure DevOps) to automate builds and deployments. Strong collaborator in Agile and remote teams, passionate about building efficient, maintainable systems.",
                            Title = "C# /.NET Developer",
                            Url = "GitHub / LinkedIn (@wisdomf41)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
